name: dagscan

services:
  mssql:
    container_name: dagscan.sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword
    networks:
      - backend

  dagscan.worker:
    image: dagscan.worker
    container_name: dagscan.worker
    build:
      context: .
      dockerfile: dagscan.worker/Dockerfile
    env_file:
      - .env
      - .env.local
    depends_on:
      mssql:
        condition: service_started
    networks:
      - backend

  dagscan.api:
    image: dagscan.api
    container_name: dagscan.api
    ports:
      - ${DAGSCAN_API_HTTP_PORT}:8080
      - ${DAGSCAN_API_HTTPS_PORT}:8081
    build:
      context: .
      dockerfile: dagscan.api/Dockerfile
    env_file:
      - .env
      - .env.local
    depends_on:
      mssql:
        condition: service_started
    networks:
      - backend

networks:
  backend: {
    driver: bridge
  }
